services:
  migration_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: source_db
    ports:
      - "5432:5432"
    volumes:
      - migration_db_data:/var/lib/postgresql/data

  source_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - source_db_data:/var/opt/mssql



volumes:
  migration_db_data:
  source_db_data: